services:
  db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle_db
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      ORACLE_PWD: YourSysPwd
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - oracle-xe-data:/opt/oracle/oradata
      - ./oracle-init/setup:/opt/oracle/scripts/setup
    healthcheck:
      test: ["CMD-SHELL", "echo 'select 1 from dual;' | sqlplus -s system/YourSysPwd@localhost:1521/XEPDB1 || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 30

  db-init:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./oracle-init/setup:/opt/oracle/scripts/setup
    entrypoint:
      - bash
      - -lc
      - |
        echo "$(date +'%F %T') Running schema scripts..."
        sqlplus -s system/"YourSysPwd"@db:1521/XEPDB1 @/opt/oracle/scripts/setup/01_users_and_schema.sql
        sqlplus -s system/"YourSysPwd"@db:1521/XEPDB1 @/opt/oracle/scripts/setup/02_seed.sql
        echo "$(date +'%F %T') Done."
    restart: "no"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@db:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: LOAN_SYSTEM
      SPRING_DATASOURCE_PASSWORD: LoanSystem123
    ports:
      - "8080:8080"

volumes:
  oracle-xe-data:
