-- 01_users_and_schema.sql (idempotent)
WHENEVER SQLERROR EXIT SQL.SQLCODE
SET ECHO ON

DECLARE
  v_cnt NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_cnt FROM dba_users WHERE username = 'LOAN_SYSTEM';
  IF v_cnt = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER LOAN_SYSTEM IDENTIFIED BY "LoanSystem123" DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP QUOTA UNLIMITED ON USERS';
  ELSE
    EXECUTE IMMEDIATE 'ALTER USER LOAN_SYSTEM IDENTIFIED BY "LoanSystem123"';
  END IF;
END;
/
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE TRIGGER TO LOAN_SYSTEM;
GRANT CONNECT, RESOURCE TO LOAN_SYSTEM;

ALTER SESSION SET CURRENT_SCHEMA = LOAN_SYSTEM;

BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE CUSTOMER_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
BEGIN
  EXECUTE IMMEDIATE 'CREATE SEQUENCE LOAN_APP_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
PROMPT User ensured and sequences ensured.
